In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#2024-2025 season database
#important because when betting player prop, the team that has higher odd of winning usually hits 
#exception may include blow outs (30+)
#Also can reference previous match ups
#Players' favorite shot vs team shot %, etc

file_path = 'data/2024-2025.csv'
df_2024_2025 = pd.read_csv(file_path, delimiter=',') 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df_2024_2025.head()

,Rk,Team,Date▲,PTS,Unnamed: 4,Opp,Result,MP,FG,FGA,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%,PTS.1,FG.1,FGA.1,FG%.1,2P.1,2PA.1,2P%.1,3P.1,3PA.1,3P%.1,FT.1,FTA.1,FT%.1,PTS.2
0,1,MIN,2024-10-22,103,@,LAL,L 103-110,240,35,85,0.412,22,44,0.500,13,41,0.317,20,27,0.741,103,42,95,0.442,37,65,0.569,5,30,0.167,21,25,0.840,110
1,2,NYK,2024-10-22,109,@,BOS,L 109-132,240,43,78,0.551,32,48,0.667,11,30,0.367,12,16,0.750,109,48,95,0.505,19,34,0.559,29,61,0.475,7,8,0.875,132
2,3,LAL,2024-10-22,110,NaN,MIN,W 110-103,240,42,95,0.442,37,65,0.569,5,30,0.167,21,25,0.840,110,35,85,0.412,22,44,0.500,13,41,0.317,20,27,0.741,103
3,4,BOS,2024-10-22,132,NaN,NYK,W 132-109,240,48,95,0.505,19,34,0.559,29,61,0.475,7,8,0.875,132,43,78,0.551,32,48,0.667,11,30,0.367,12,16,0.750,109
4,5,MIA,2024-10-23,97,NaN,ORL,L 97-116,240,32,82,0.390,21,48,0.438,11,34,0.324,22,29,0.759,97,41,96,0.427,23,47,0.489,18,49,0.367,16,22,0.727,116

In [57]:
#Will take forever to clean, will do it when I move on to machine learning

# 2024-10-30
## PrizePick
### NBA 1Q
Lines available: 
1. **ATL vs WAS:** Trae Young 6.5 PT, Jordan Poole 5.5 PT, Jalen Johnson 4.5 PT, Bilal Coulibaly 3.5 PT | 0.5 Ass, Clint Capela 3.5 PT | 2.5 REB
2. **IND vs BOS:** Derrick White 3.5 PT, Andrew Nembhard 2.5 PT | 0.5 REB, Pascal Siakam 4.5 PT, Tyrese Haliburton 4.5 PT, Myles Turner 1.5 REB, Jaylen Brown 1 ASS
3. **CHA vs TOR:** Lamelo Ball 6 PT, Jakob Poeltl 3.5 PT | 2.5 REB, Miles Bridges 4 PT | 1.5 REB, Ochai Agbaji 2.5 PT, Seth Curry 2.5 PT | 0.5 REB, RJ Barrett 5 PT, Tre Mann 0.5 ASS
4. **OKC vs SAS:** Victor Wembanyama 5.5 PT, Shai Gilgeous-Alexander 7.5 PT, Jeremy Sochan 4 PT, Chet Holmgren 4.5 PT, Harrison Barnes, 2.5 PT, Jalen Williams 4 PT, Lugentz Dort 2.5 PT
5. **CLE vs LAL:** Anthony Davis 8 PT, Darius Garland 4.5 PT | 0.5 REB, Austin Reaves 4 PT, Dean Wade 0.5 PT, Donovan Mitchell 6 PT, Lebron James 4 PT, Evan Mobley 4 PT, Rui Hachimura 3.5 PT, Jarrett Allen 4.5 PT | 0.5 ASS
6. **PHI vs DET:** Cade Cunningham 5.5 PT, Tyrese Maxey 7.5 PT, Kelly Oubre Jr. 4.5 PT, Tobias Harris 3.5 PT | 0.5 ASS, Andre Drummond 2.5 PT, Caleb Martin 2.5 PT, Tim Hardaway Jr. 2.5 PT
7. **MIA vs NYK:** Jimmy Butler 4.5 PT, Tyler Herro 4.5 PT, Mikal Bridges 4.5 PT, OG Anunoby 3.5 PT, Karl-Anthony Towns 2.5 REB, Bam Adebayo 2.5 REB
8. **LAC vs POR:** James Harden 6.5 PT, Anfernee Simons 5 PT, Normal Powell 4.5 PT, Jerami Grant 5 PT, Ivica Zubac 5 PT, Deandre Ayton 5 PT, Derrick Jones Jr. 2.5 PT, Deni Avdija 3.5 PT, Terance Mann 2.5 PT

### ESPN Bettings odds
1. Hawks vs Wizards | Matchup Prediction: 70-30 | ML: ATL -190 | Total O/U: 233.5 | Spread: ATL -5.5
2. Celtics vs Pacers | Matchup Prediction: 69 - 31 | ML: BOS -250 | Total O/U: 235.5 | Spread: BOS - 6.5
3. Raptors vs Hornets | Matchup Prediction 29 - 71 | ML: CHA -235 | Total O/U: 224.5 | Spread: CHA - 6.5
4. Thunders vs Spurs | Matchup Prediction: 23 - 77 | ML: OKC -1000 | Total O/U: 220.5 | Spread: OKC - 12.5
5. Lakers vs Cavaliers | Matchup Prediction: 35 - 65 | ML: CAV -190 | Total O/U: 225.5 | Spread: CLE - 4.5
6. Pistons vs 76ers | Matchup Prediction: 52.5 - 47.5 | ML: PHI -180 | Total O/U: 218.5 | Spread: PHI -4.5
7. Heat vs Knicks | Matchup Prediction: 40-60 | ML: NYK -120 | Total O/U 215.5 | Spread: NYK -1.5
8. Trailblazers vs Clippers | Matchup Prediction: 38 - 62 | ML: LAC -340 | Total O/U 219.5 | Spread LAC -8.5

Notes:
1. We usually like even, or slightly favored matches instead of blow outs.
2. If Total O/U is high, we bet points, if low, we bet rebounds.
3. Assist is wonky but nothing stops a random hand off 3 pointer, so 0.5 assist is good if the guy plays 9 minutes + in the first quarter.
4. Today's line up, I personally would like to look into DET/PHI, MIA/NYK, TOR/CHA (Huge Lamelo fan)

Steps: Detroit Pistons vs Philadelphia 76ers
1. 76er slight favor but Pistons have been playing well despite being 0-4, 3/4 are single digit lost and they played against all playoff teams from last year.
2. Against an injured 76ers team, I think Pistons are hungry to prove themselves.
3. Looking into Cade Cunningham as he average 26.5 PPG  & 36.8 MPG
4. He is their first option in offense as a scoring point guard (lowkey kind of popular right now)
5. So I am going to look into his 1Q stats dating back to 2023 season.
6. Cade Cunningham: 5.5 PT
7. I don't know why stathead is doesn't have 10-28-2024's game against Miami, but Cade does not look good.
8. Honestly at this point, I am not a big fan of 1Q. I am going to end it here and continue to the whole game.

In [84]:
#Cade Cunningham Stats
df_cade = pd.read_csv('data/cadecunningham1q.csv', delimiter=',') 
df_cade['Date'] = pd.to_datetime(df_cade['Date▼'], format='%Y-%m-%d')
twozerotwofour_df_cade = df_cade[df_cade['Date▼'] >= '2024-10-20']
total_games_played = df_cade.shape[0]
total_games_played_2024 = twozerotwofour_df_cade.shape[0]
zero_count = (df_cade['PTS'] == 0).sum()
average_pts = df_cade['PTS'].mean()
under_fivepointfive = (df_cade['PTS'] < 6).sum()
zero_count_2024 = (twozerotwofour_df_cade['PTS'] == 0).sum()
average_pts_2024 = twozerotwofour_df_cade['PTS'].mean()
under_fivepointfive_2024 = (twozerotwofour_df_cade['PTS'] <6).sum()
print(f"Total Games Played (2024): {total_games_played}")
print(f"Number of Zeros in PTS: {zero_count}")
print(f"Average PTS: {average_pts}")
print(f"Under 5.5 PTS: {under_fivepointfive}")
print(f"Total Games Played (2024): {total_games_played_2024}")
print(f"Number of Zeros in PTS (2024): {zero_count_2024}")
print(f"Average PTS (2024): {average_pts_2024}")
print(f"Under 5.5 PTS (2024): {under_fivepointfive_2024}")

Total Games Played (2024): 65
Number of Zeros in PTS: 8
Average PTS: 5.2153846153846155
Under 5.5 PTS: 35
Total Games Played (2024): 3
Number of Zeros in PTS (2024): 1
Average PTS (2024): 3.6666666666666665
Under 5.5 PTS (2024): 2